.TH EMP_SERVER 6
.SH NAME
emp_server \- Empire server
.SH SYNOPSIS
.B emp_server
[
.BI \-dhpsv
]
[
.BI \-e " configfile"
]
.br
.SH DESCRIPTION
.I emp_server
is a daemon which listens to the Empire port for players connecting to
the game.  For more information on the game of Empire, see the info
pages within the game.
.SH OPTIONS
.TP
.B \-d 
Debug mode.  This will prevent the server from forking itself into the
background.  It will also make it abort when it detects an internal
error.  You normally want to use this flag if you are running
.I emp_server
from within a debugger.
.TP
.BI \-e " configfile"
Use game configuration specification in 
.I configfile
\&.  By default, the file "econfig" in the data directory is used.
.TP
.B \-h 
Help.  Print brief usage information and exit.
.TP
.B \-p
Threading debug mode.  Implies -d.
.TP
.B \-s
Enable thread stack checking.
.TP
.B \-v
Print version information and exit.
.SH OPERANDS
Operands are ignored for backward compatibility.  Their use is
deprecated.
.SH BUGS
Please report all bugs to the Wolfpack <wolfpack@wolfpackempire.com>
.SH AUTHORS
Dave Pare, Jeff Bailey, Thomas Ruschak, Ken Stevens and Steve McClure
are principal authors.  The full list of authors is too long to
mention here.
