.TH EMPSCHED 1
.SH NAME
empsched \- Print Empire update schedule
.SH SYNOPSIS
.B empsched
[
.B \-hv
]
[
.BI \-e " configfile"
]
[
.BI \-n " number"
]
[
.I file
]
.br
.SH DESCRIPTION
.B empsched
prints the Empire update schedule.
.SH OPTIONS
.TP
.BI \-e " configfile"
Use game configuration in \fIconfigfile\fR.
.TP
.B \-h 
Help.  Print brief usage information and exit.
.TP
.BI \-n " number"
Print \fInumber\fR updates.
.TP
.B \-v
Print version information and exit.
.SH OPERANDS
If \fIfile\fR is given, \fBempsched\fR prints the schedule defined
there instead of the current schedule.
.SH "SEE ALSO"
\fIemp_server\fR(6).
.SH AUTHOR
Markus Armbruster <armbru@pond.sub.org>
