.TH FAIRLAND 6
.SH NAME
fairland \- Empire land generator
.SH SYNOPSIS
.B fairland
[\fIoption\fP]...
\fInc\fP
\fIsc\fP
[\fIni\fP
[\fIis\fP
[\fIsp\fP
[\fIpm\fP
[\fIdi\fP
[\fIid\fP]]]]]]
.br
.SH DESCRIPTION
.B fairland
is a program which creates land for Empire.  It should be run after
.I files
has been run and before
.I emp_server
has been started.  It creates a specified number of start islands
("continents"), and spaces them evenly accross the map.  It makes all
of them the same size, and makes sure that they don't meet.  It gives
each start island exactly the same distribution of resources and the
same number of mountains.  Different arguments produce quite different
kinds of maps.
.SH OPTIONS
.TP
.BI \-e " configfile"
Use game configuration in \fIconfigfile\fR.
.TP
.B \-h
Help.  Print brief usage information and exit.
.TP
.B \-i
Islands will crash into each other and merge.
.TP
.B \-q
Run quietly without printing anything to the terminal.
.TP
.BI \-R " seed"
Use
.I seed
as seed for the pseudo-random number generator.  This can be used to
reproduce a previously created world.  The seed used to generate a
world is printed along with the map.
.TP
.BI \-s " script"
Write script to add countries and sanctuaries to file \fIscript\fP
(default "newcap_script").
.TP
.B \-v
Print version information and exit.
.SH OPERANDS
.TP
.I nc
number of continents
.TP
.I sc
continent size
.TP
.I ni
number of additional islands (default \fInc\fP)
.TP
.I is
average size of additional islands (default \fIsc\fP/2)
.TP
.I sp
land spikiness (in percent, default 10), low values result in rounded
islands, high values result in tentacles
.TP
.I pm
how much of each island is mountain (in percent, default 0)
.TP
.I di
minimum distance between continents (default 2)
.TP
.I id
minimum distance between additional islands and continents (default 1)
.SH AUTHOR
Ken Stevens <children@empire.net>
