.TH FILES 6
.SH NAME
files \- Empire file initialization
.SH SYNOPSIS
.B files
[
.B \-fhv
]
[
.BI \-e " configfile"
]
.br
.SH DESCRIPTION
.B files
creates all of the files which are required by
.B emp_server
to run a game.  It will destroy all previous game data, so excercise
caution when running this program.
.SH OPTIONS
.TP
.BI \-e " configfile"
Use game configuration in \fIconfigfile\fR.
.TP
.B \-f
Clobber existing game data without asking for confirmation.
.TP
.B \-h
Help.  Print brief usage information and exit.
.TP
.B \-v
Print version information and exit.
.SH "SEE ALSO"
\fIemp_server\fR(6).
