.TH PERFECT 1
.UC
.SH NAME
perfect \- create perfect resources
.SH SYNOPSIS
.B perfect
[
.BI \-e\ configfile
]
[
.BI \-s\ sectfile
]
.br
.SH DESCRIPTION
While most deities prefer to use
.I fairland
to generate their resources, this program is included as an alternative for
creating the resources for a game.  It sets all resources to 100.
.SH OPTIONS
.TP
.BI \-e\ configfile
causes
.I perfect
to use the game configuration specified in 
.I configfile
(by default, the file "econfig" in the data directory is used)
.TP
.BI \-s\ sectfile
give resources to the sectors in 
.I sectfile
(default is the "sector" file in the data directory)
