#!/bin/sh -e
# Acts of god test for Empire

if [ $# -ne 1 ]
then echo "Usage: $0 SRCDIR" >&2; exit 1
fi

srcdir="$1"

. "$srcdir"/tests/test-common.sh

create_sandbox
cat >>sandbox/etc/empire/econfig <<EOF
WORLD_X 24
WORLD_Y 16
GODNEWS 1
EOF

begin_test "$srcdir"/tests/actofgod/init_script

perl "$srcdir"/tests/actofgod/geninput.pl | feed_input POGO peter

end_test

cmp_out var/empire/server.log var/empire/journal.log final.xdump
