#!/bin/sh -e
# Build test for Empire

if [ $# -ne 1 ]
then echo "Usage: $0 SRCDIR" >&2; exit 1
fi

srcdir="$1"

. "$srcdir"/tests/test-common.sh

create_sandbox
cat >>sandbox/etc/empire/econfig <<EOF
WORLD_X 20
WORLD_Y 12
BRIDGETOWERS 1
EOF
# TODO cover drnuke_const 0.33

begin_test "$srcdir"/tests/build/setup-POGO
feed_dir "$srcdir"/tests/build/units
feed_dir "$srcdir"/tests/build/bridges-1
stop_server
cat >>sandbox/etc/empire/econfig <<EOF
EASY_BRIDGES 0
BRIDGETOWERS 0
EOF
start_server
feed_dir "$srcdir"/tests/build/bridges-2
end_test

cmp_out var/empire/server.log var/empire/journal.log final.xdump
