#!/bin/sh -e
# Basic files test

if [ $# -ne 1 ]
then echo "Usage: $0 SRCDIR" >&2; exit 1
fi

srcdir="$1"

. "$srcdir"/tests/test-common.sh

create_sandbox

exec 3>sandbox/files.out

$files -f >&3

exec 3>&-

$empdump -x >sandbox/final.xdump

cmp_out files.out final.xdump
