#!/bin/sh -e
# Gun fire test for Empire

if [ $# -ne 1 ]
then echo "Usage: $0 SRCDIR" >&2; exit 1
fi

srcdir="$1"

. "$srcdir"/tests/test-common.sh

create_sandbox
cat >>sandbox/etc/empire/econfig <<EOF
WORLD_X 32
WORLD_Y 16
EASY_BRIDGES 1
EOF

begin_test "$srcdir"/tests/fire/setup-POGO
feed_dir "$srcdir"/tests/fire
end_test

cmp_out var/empire/server.log var/empire/journal.log final.xdump
