#!/bin/sh -e
# Documentation completeness test for Empire

if [ $# -ne 1 ]
then echo "Usage: $0 SRCDIR" >&2; exit 1
fi

srcdir="$1"

. "$srcdir"/tests/test-common.sh

create_sandbox

begin_test <<EOF
add 1 1 1 p
des 0:2,0 -
newcap 1 0,0
add 2 visitor visitor v
nat
nat 1
nat 2
EOF

feed_input POGO peter <<EOF
list >sandbox/deity.list
EOF
feed_input 1 1 <<EOF
list >sandbox/sanctuary.list
break
list >sandbox/active.list
EOF
feed_input visitor visitor <<EOF
list >sandbox/visitor.list
EOF

end_test

if perl $srcdir/tests/info/cmp-toc-vs-lists.pl info/toc sandbox/*.list
then echo "Command documentation OK"
else echo "Command documentation FAIL"; false
fi
