#!/bin/sh -e
# Load/unload test for Empire

if [ $# -ne 1 ]
then echo "Usage: $0 SRCDIR" >&2; exit 1
fi

srcdir="$1"

. "$srcdir"/tests/test-common.sh

create_sandbox
cat >>$econfig <<EOF
WORLD_X 24
WORLD_Y 12
NO_PLAGUE 0
MARKET 1
EOF
customize big-city
# TODO actually cover plague and market
# TODO observe land unit fortification
# TODO observe mission and retreat orders

begin_test "$srcdir"/tests/load-tend/setup-POGO
feed_dir "$srcdir"/tests/load-tend
end_test

cmp_logs_xdump
