#!/bin/sh -e
# Ship and land unit retreat test for Empire

if [ $# -ne 1 ]
then echo "Usage: $0 SRCDIR" >&2; exit 1
fi

srcdir="$1"

. "$srcdir"/tests/test-common.sh

create_sandbox
cat >>$econfig <<EOF
WORLD_X 24
WORLD_Y 12
MARKET 1
EOF
customize big-city
# TODO cover RAILWAYS 0

begin_test "$srcdir"/tests/retreat/setup-POGO "$srcdir"/tests/retreat/setup-2
feed_dir "$srcdir"/tests/retreat
end_test

cmp_logs_xdump
