#!/bin/sh -e
# version test for Empire

if [ $# -ne 1 ]
then echo "Usage: $0 SRCDIR" >&2; exit 1
fi

srcdir="$1"

. "$srcdir"/tests/test-common.sh

create_sandbox

begin_test "$srcdir"/tests/version/setup-POGO

feed_dir "$srcdir"/tests/version/default

stop_server

cat >>$econfig <<EOF
ALL_BLEED 0
MARKET 1
MOB_ACCESS 1
RES_POP 1
game_days "Su Mo Tu We Th Fr Sa"
game_hours "00:00-24:00"
tech_log_base 0
EOF
customize big-city
# TODO cover drnuke_const 0.33

start_server

feed_dir "$srcdir"/tests/version/fancy

end_test

cmp_out var/empire/server.log var/empire/journal.log
